[versions]
algoutils = "0.7.2"


[plugins]
algomate = { id = "org.tudalgo.algomate", version = "0.6.1" }
style = { id = "org.sourcegrade.style", version = "2.1.0" }
jagr = { id = "org.sourcegrade.jagr-gradle", version = "0.10.2" }

[libraries]
algoutils-tutor = { module = "org.tudalgo:algoutils-tutor", version.ref = "algoutils" }
junit-pioneer = { module = "org.junit-pioneer:junit-pioneer", version = "2.2.0" }
